### ISSUE TITLE
Read Power consumption

### ISSUE THREAD

**Issue by Giorgiofox** [wr/homebridge-mpower#2]
Hello, 
have you planned to read power consumption?

thanks

**Comment by wr** [comment]
no plans at this point :)

**Comment by Giorgiofox** [comment]
Thanks for your very fast reply. 
Do you want to help me to get Volt and watt from mPower 6?

**Comment by wr** [comment]
sure! submit a PR :)

**Comment by Giorgiofox** [comment]
This is the output of the curl of my mPower PRO 6 (so I can confirm that your plugin work very well with this "6" version)
Can you please explain me how you read status of output?
I cannot find any parse in index.js for reading the status of "output" or "relay"
I'm not good with JS ;) please be patient. 

Have you idea of what type of service we can use for power and voltage readings in homebridge / homekit? We need to create sensors with this vaules

 

`{
	"sensors": [{
		"port": 1,
		"output": 1,
		"power": 0.0,
		"enabled": 0,
		"current": 0.0,
		"voltage": 229.339153289,
		"powerfactor": 0.0,
		"relay": 1,
		"lock": 0,
		"thismonth": 0
	}, {
		"port": 2,
		"output": 1,
		"power": 0.0,
		"enabled": 0,
		"current": 0.0,
		"voltage": 229.337946176,
		"powerfactor": 0.0,
		"relay": 1,
		"lock": 0,
		"thismonth": 0
	}, {
		"port": 3,
		"output": 0,
		"power": 0.0,
		"enabled": 0,
		"current": 0.0,
		"voltage": 0.0,
		"powerfactor": 0.0,
		"relay": 0,
		"lock": 0,
		"thismonth": 0
	}, {
		"port": 4,
		"output": 0,
		"power": 0.0,
		"enabled": 0,
		"current": 0.0,
		"voltage": 0.0,
		"powerfactor": 0.0,
		"relay": 0,
		"lock": 0,
		"thismonth": 0
	}, {
		"port": 5,
		"output": 0,
		"power": 0.0,
		"enabled": 0,
		"current": 0.0,
		"voltage": 0.0,
		"powerfactor": 0.0,
		"relay": 0,
		"lock": 0,
		"thismonth": 0
	}, {
		"port": 6,
		"output": 0,
		"power": 0.0,
		"enabled": 0,
		"current": 0.0,
		"voltage": 0.0,
		"powerfactor": 0.0,
		"relay": 0,
		"lock": 0,
		"thismonth": 0
	}],
	"status": "success"
}`

**Comment by pponce** [comment]
i think this is the part of the code that parses the output value which is the value for if the socket is getting power or not.
so you would need to add state.sensors[0].power readings.
i'm also new to all this but this is my guess.
    
      if (stdout != "") {
            var state = JSON.parse(stdout);
            if(state.sensors[0].output == 1) {
              callback(null, true);
            } else if(state.sensors[0].output == 0) {
              callback(null, false);
            }

**Comment by pponce** [comment]
i just submitted a PR that will correctly set the "out let in use" parameter if something is plugged into the outlet. So you can tell if the outlet has power and is being used or if it just has power but nothing is plugged in.
This request checks for "output" status. Essentially if the outlet has power or not.
curl -b "AIROS_SESSIONID=' + this.airos_sessionid + '" ' + this.url + '/sensors/' + this.id + '/output';

This request returns the power value.
curl -b "AIROS_SESSIONID=' + this.airos_sessionid + '" ' + this.url + '/sensors/' + this.id + '/power';

for every value in your output you can request the current state of that value by changing the request to match what you are looking for.

**Comment by wr** [comment]
fixed by #4 i believe
