### ISSUE TITLE
not working for Ubiquiti mPower mFi 3-port Power

### ISSUE THREAD

**Issue by pponce** [wr/homebridge-mpower#3]
I just purchased the 3 port power version. I've installed the plugin and the three ports appear in homekit but they don't actually turn the power on and off.
Before installing i did update the firmware to the latest version 2.1.11
https://www.ubnt.com/download/mfi/mpower/mpower/firmwarebin

Should i be using an older firmware?
Wish i had checked the plugin before updating.

**Comment by pponce** [comment]
i was able to login in via the webserver to the device and see my session ID.
I was then able to execute this curl url to turn on and off the socket by changing the output value to 1 and then 0.
curl -X PUT -d output=1 -b "AIROS_SESSIONID=26bd215e762a06489a203fb6d0ff43c2" 192.168.1.128/sensors/1

i also tried with authenticate with a random value for the session ID and then ran a command with that value and it worked. 
I'll have to dig deeper to figure this out.

**Comment by wr** [comment]
Hi @pponce, I'm running 2.1.11 as well, and I'm able to control my single-outlet switch.

Could you paste here your config.json file? Be sure to remove any sensitive info like passwords or public domains / IPs.

Was about to ask you to try manually `curl`ing, but it looks like you already tried that successfully :)

What does the output of `homebridge` look like in your terminal when you try switching on and off from the Home app?

**Comment by pponce** [comment]
Thanks for the reply. So it looks like I do have it working and perhaps the particular app I was using to test is the issue.
When using the apple home app that comes with iOS 10 it works!
My other app is also called home but it's the one in the App Store that cost 15 bucks. I'm unable to turn the outlets on or off with that app.
It shows corect on and off status though. Just can't turn things on and off with this app.
Perhaps it's the "outlet" type that it does not support?
So it does work with apples home app so I'm happy.
How does one expose the outlet to HomeKit as type "switch" to see if that is the issue?

**Comment by wr** [comment]
good to hear! never used that other home app before – i've always just used the home app.

if you want to debug by making it a 'switch' service instead of an 'outlet' you could just do a text substitution in index.js from `outlet` to `switch` and it should(?) work – you'll need to modify your config.json too probably.

**Comment by pponce** [comment]
I'll give it a go.
Thanks for this. It's awesome to see all these devices being supported.


Get Outlook for iOS<https://aka.ms/o0ukef>




On Thu, Dec 29, 2016 at 4:10 PM -0800, "Wells Riley ✨" <notifications@github.com<mailto:notifications@github.com>> wrote:


good to hear! never used that other home app before – i've always just used the home app.

if you want to debug by making it a 'switch' service instead of an 'outlet' you could just do a text substitution in index.js from outlet to switch and it should(?) work – you'll need to modify your config.json too probably.

**Comment by pponce** [comment]
I made it appear to homekit as a switch but still no luck with getting it to work outside of the stock apple app.

I've tried these two homekit apps and they both don't work.
https://itunes.apple.com/us/app/home-smart-home-automation/id995994352?mt=8
https://itunes.apple.com/us/app/hesperus/id969348892?mt=8

It's odd because all my other homebridge plugins work with all my homekit apps. And i'm using plenty.
philips (for exposing non hue lights to homekit), homebridge-script, big ass fans plugin, nest, gpio plugin, Chamberlain garage door plugin and more. 

Glad it works with the default home app though so not complaining but you might get others that notice it doesn't "work" and this might be the reason. Hesperus is free so you could see what i'm running into when i use the non apple home app.

**Comment by pponce** [comment]
oh and if i figure it out i'll let you know. All this homekit stuff is new to me though.

**Comment by wr** [comment]
cool, thanks for that info. i'm not sure why non-apple apps would be the issue... maybe i'll look into it if enough people have similar issues :)

**Comment by pponce** [comment]
I figured out the issue with non apple homekit apps.
Within your setState function you need to add this line before the cmdUpdate variable declaration.
state = (state == true || state == 1) ? 1 : 0;

For some reason the state variable comes in as false or true in the non apple homekit app and in the apple homekit app it comes in as 0 or 1.
The update command was failing in the non apple apps because of this.

i'm still learning how to use github and don't know how to maintain two branches yet (one with your code where i could PR this simple change and one for me to test things with).

But if you add that one line then apple homekit and non apple homekit apps appear to both work.

**Comment by pponce** [comment]
just figured out how to do the PR with your base branch.
you should see it now.
